{
    'name': 'Dispatch Shift',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Manage temporary workforce dispatch shifts',
    'depends': ['hr_recruitment', 'portal'],
    'data': [
        'security/dispatch_shift_security.xml',
        'security/ir.model.access.csv',
        'views/dispatch_employee_views.xml',
        'views/hr_job_views.xml',
        'views/dispatch_campaign_views.xml',
        'views/dispatch_campaign_invite_views.xml',
        'views/dispatch_shift_template_views.xml',
        'views/dispatch_shift_slot_views.xml',
        'views/dispatch_shift_application_views.xml',
        'views/menus.xml',
        'data/mail_data.xml',
        'templates/portal.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'dispatch_shift/static/src/scss/portal.scss',
            'dispatch_shift/static/src/js/dispatch_portal.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
